apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: auth
  name: authorization-server
  labels:
    app: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authorization-server
  template:
    metadata:
      labels:
        app: authorization-server
    spec:
      containers:
        - name: authorization-server
          image: ythwork/authorization-server:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k3s
          