apiVersion: v1
kind: Service
metadata:
  name: authorization-server
  labels:
    app: authorization-server
spec:
  type: ClusterIP
  selector:
    app: authorization-server
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080