apiVersion: cert-manager.io/v1
kind: Certificate 
metadata:
  name: auth-local-cert
spec:
  secretName: auth-local-tls
  dnsNames:
    - ythworkcom
    - "*.ythwork.com"
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer 