resources:
  - authorization-server-deployment.yaml
  - authorization-server-service.yaml
  - resource-server-deployment.yaml
  - resource-server-service.yaml
  - ingress.yaml
  - issuer.yaml
  - certificate.yaml
  - auth-jwt-key.yaml